# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_7/design_1_axi_dma_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_7 || ORIG_REF_NAME==design_1_axi_dma_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_8/design_1_axi_dma_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_8 || ORIG_REF_NAME==design_1_axi_dma_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_9/design_1_axi_dma_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_9 || ORIG_REF_NAME==design_1_axi_dma_0_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_10/design_1_axi_dma_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_10 || ORIG_REF_NAME==design_1_axi_dma_0_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_0/design_1_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_0 || ORIG_REF_NAME==design_1_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_1_1/design_1_axi_mem_intercon_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_1_1 || ORIG_REF_NAME==design_1_axi_mem_intercon_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_2_1/design_1_axi_mem_intercon_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_2_1 || ORIG_REF_NAME==design_1_axi_mem_intercon_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_3_1/design_1_axi_mem_intercon_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_3_1 || ORIG_REF_NAME==design_1_axi_mem_intercon_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_5/design_1_xbar_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_5 || ORIG_REF_NAME==design_1_xbar_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_3 || ORIG_REF_NAME==design_1_auto_pc_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_4/design_1_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_4 || ORIG_REF_NAME==design_1_auto_pc_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4StreamConstant32_0_0/design_1_AXI4StreamConstant32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI4StreamConstant32_0_0 || ORIG_REF_NAME==design_1_AXI4StreamConstant32_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4StreamConstant32_0_1/design_1_AXI4StreamConstant32_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI4StreamConstant32_0_1 || ORIG_REF_NAME==design_1_AXI4StreamConstant32_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4StreamConstant32_0_2/design_1_AXI4StreamConstant32_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI4StreamConstant32_0_2 || ORIG_REF_NAME==design_1_AXI4StreamConstant32_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4StreamConstant32_0_3/design_1_AXI4StreamConstant32_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI4StreamConstant32_0_3 || ORIG_REF_NAME==design_1_AXI4StreamConstant32_0_3} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
