# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/joaovieira/reconfigurable_computing/xilinx/pl2ps_64bit/BandwidthAssessment.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_7/design_1_axi_dma_0_7.xci
# IP: The module: 'design_1_axi_dma_0_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/joaovieira/reconfigurable_computing/xilinx/pl2ps_64bit/BandwidthAssessment.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_7/design_1_axi_dma_0_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_7'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/joaovieira/reconfigurable_computing/xilinx/pl2ps_64bit/BandwidthAssessment.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_7/design_1_axi_dma_0_7.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/joaovieira/reconfigurable_computing/xilinx/pl2ps_64bit/BandwidthAssessment.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_7/design_1_axi_dma_0_7_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/joaovieira/reconfigurable_computing/xilinx/pl2ps_64bit/BandwidthAssessment.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_7/design_1_axi_dma_0_7.xci
# IP: The module: 'design_1_axi_dma_0_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/joaovieira/reconfigurable_computing/xilinx/pl2ps_64bit/BandwidthAssessment.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_7/design_1_axi_dma_0_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/joaovieira/reconfigurable_computing/xilinx/pl2ps_64bit/BandwidthAssessment.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_7/design_1_axi_dma_0_7.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/joaovieira/reconfigurable_computing/xilinx/pl2ps_64bit/BandwidthAssessment.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_7/design_1_axi_dma_0_7_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
