# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/joaovieira/reconfigurable_computing/xilinx/ps2pl_64bit/BandwidthAssessment.srcs/sources_1/bd/design_1/ip/design_1_xbar_5/design_1_xbar_5.xci
# IP: The module: 'design_1_xbar_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/joaovieira/reconfigurable_computing/xilinx/ps2pl_64bit/BandwidthAssessment.srcs/sources_1/bd/design_1/ip/design_1_xbar_5/design_1_xbar_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_5'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/joaovieira/reconfigurable_computing/xilinx/ps2pl_64bit/BandwidthAssessment.srcs/sources_1/bd/design_1/ip/design_1_xbar_5/design_1_xbar_5.xci
# IP: The module: 'design_1_xbar_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/joaovieira/reconfigurable_computing/xilinx/ps2pl_64bit/BandwidthAssessment.srcs/sources_1/bd/design_1/ip/design_1_xbar_5/design_1_xbar_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
